ionos-cloud/ionosctl

- .gitignore
- Makefile
To my knowledge it is common practice to invoke a compile/build target when calling `make` without arguments.
> Use build as default target

- .gitignore
- Makefile
- commands/datacenter.go
- commands/lan.go
- commands/loadbalancer.go
- commands/location.go
- commands/nic.go
- commands/request.go
- commands/server.go
- commands/volume.go
- pkg/builder/command.go
- pkg/config/config.go
- pkg/config/config_test.go
This makes the CLI less reliant on the config file and allows to use it without calling `login` first.
Fallback is only used when the config file is not found.
> Use environment variables as auth config fallback

- Makefile
Makefile uses `?=` to define a variable that is set if the variable on the left side is not defined. This also fixes the binary name when running `make build`.
Additionally, ensure that the docs directory exists before updating.
Before:
```sh
$ make
--- Building ionosctl via go build ---
built /home/mv/Projects/CORE/ionosctl/builds/ionosctl__
DONE
```
After:
```sh
make
--- Building ionosctl via go build ---
built /home/mv/Projects/CORE/ionosctl/builds/ionosctl_linux_amd64
DONE
```
> Use Makefile syntax to define defaults

- pkg/utils/printer/printer.go
- pkg/utils/printer/printer_test.go
- pkg/utils/wait.go
- pkg/utils/wait_test.go
Use a regex to extract the request ID instead of checking for the hard-coded default v5 API URL.
This also should fix printing in general for non-default API URLs, like staging.
> Fix wait for non-default API URLs

- README.md
- commands/backupunit.go
- commands/cdrom.go
- commands/datacenter.go
- commands/firewallrule.go
- commands/group.go
- commands/image.go
- commands/ipblock.go
- commands/k8s_cluster.go
- commands/k8s_node.go
- commands/k8s_nodepool.go
- commands/login.go
- docs/README.md
- pkg/config/config.go
- pkg/config/config_test.go
- pkg/config/constants.go
- pkg/core/command_runner.go
- pkg/resources/v5/client.go
- pkg/testdata/config.json
API URL is stored as `userdata.api-url` in the config file when `login` command is called. Subsequent calls read the URL from the config file.
The API URL can also be set via `IONOS_API_URL` environment variable.
This variable name is also used by the [terraform provider].
The sources for API URL have the following priority:
1. Explicitly set `--api-url` flag
2. Config file
3. Env var `IONOS_API_URL`
4. `--api-url` default value
Other changes:
- Fix login when the value of `--api-url` ends in `cloudapi/v5`
- Use config file over env when both `IONOS_USERNAME` and `IONOS_TOKEN` are not defined, was (`IONOS_USERNAME` **or** `IONOS_PASSWORD` before)
These changes make using `ionosctl` in staging environments a lot easier.
[terraform provider]: …
> Store API URL in config file

- commands/cloudapi-v6/completer/versions.go
- commands/cloudapi-v6/completer/versions_test.go
- commands/cloudapi-v6/k8s_cluster.go
- commands/cloudapi-v6/k8s_nodepool.go
Completion for the `--k8s-version` flag when updating a cluster or node pool. Requires necessary ID flags to be set, i.e. `--cluster-id` for clusters and `--nodepool-id` for node pools.
The completion is based on the `availableUpgradeVersions` property.
> Feat: Add completion for k8s-version flag

- commands/root.go
- internal/config/constants.go
- services/auth-v1/resources/client.go
- services/cloudapi-v6/resources/client.go
Add user agent for each client in CLI. The http user agent has the following format: 
`ionosctl/v<version>_<user-agent-sdk>`
for internal testing of the CLI it will be:
`ionosctl/DEV_<user-agent-sdk>`
> feat: add user agent [v6]

- commands/cloudapi-v6/backupunit.go
- commands/cloudapi-v6/cdrom.go
- commands/cloudapi-v6/datacenter.go
- commands/cloudapi-v6/firewallrule.go
- commands/cloudapi-v6/flowlog.go
- commands/cloudapi-v6/group.go
- commands/cloudapi-v6/image.go
- commands/cloudapi-v6/ipblock.go
- commands/cloudapi-v6/ipfailover.go
- commands/cloudapi-v6/k8s_cluster.go
- commands/cloudapi-v6/k8s_node.go
- commands/cloudapi-v6/k8s_nodepool.go
- commands/cloudapi-v6/labelresource.go
- commands/cloudapi-v6/lan.go
- commands/cloudapi-v6/loadbalancer.go
- commands/cloudapi-v6/natgateway.go
- commands/cloudapi-v6/natgateway_flowlog.go
- commands/cloudapi-v6/natgateway_rule.go
- commands/cloudapi-v6/networkloadbalancer.go
- commands/cloudapi-v6/networkloadbalancer_flowlog.go
- commands/cloudapi-v6/networkloadbalancer_rule.go
- commands/cloudapi-v6/networkloadbalancer_rule_target.go
- commands/cloudapi-v6/nic.go
- commands/cloudapi-v6/pcc.go
- commands/cloudapi-v6/s3key.go
- commands/cloudapi-v6/server.go
- commands/cloudapi-v6/snapshot.go
- commands/cloudapi-v6/user.go
- commands/cloudapi-v6/volume.go
The print that is shown when you use a delete/detach/remove operation followed by the --all flag  shows now the id and the name of the resource which will be deleted in the same line
> fix: improve verbose print when delete/detach/remove --all

- commands/cloudapi-v5/examples.go
- docs/subcommands/compute-engine/ipblock-create.md
The example and documentation for the command **ionosctl ipblock create** provided outdated parameter naming. The naming was fixed. There are no functional changes.
> Fix example and docu for ipblock create parameters

- commands/dbaas/postgres/logs.go
- commands/dbaas/postgres/logs_test.go
This PR adds validation for --since and --until options for `ionosctl dbaas postgres cluster logs list` command.
> fix: validate `--since` and `--until` options for logs

- commands/version.go
This PR updates `ionosctl version` command to display also information about SDK Go DBaaS Postgres version.
> fix: add SDK Go DBaaS Postgres info to `version`

- snap/snapcraft.yaml
Allows ionosctl to be built as a snap.
> add ionosctl as snap

- .github/workflows/release.yml
- .gitignore
- .goreleaser.yml
- CHANGELOG.md
- docs/README.md
This is adding support for publishing `ionosctl` to [Homebrew](https://brew.sh) the most widely used package manager on macOS. 
It also updates the `.gitignore` using [gitignore.io](https://www.toptal.com/developers/gitignore/) for consistency and adding quality of life for VSCode users.
> feat: Homebrew formula and .gitignore update

- README.md
- docs/README.md
missed this when code reviewing for #181 :disappointed: 
```
brew tap ionos-cloud/homebrew-ionosctl-tap
brew install ionosctl
```
should be
```
brew tap ionos-cloud/homebrew-ionos-cloud
brew install ionosctl
```
> fix: wrong brew tap name

- commands/root.go
- tools/build.sh
- tools/install.sh
add commit hash to `ionosctl version`, as well as way to distinguish if git diff is empty or not
```
% ./builds/ionosctl_linux_amd64 version
IONOS Cloud CLI version: DEV - dc7bf63
SDK GO version: 6.1.0
SDK GO DBaaS Postgres version: v1.0.3
SDK GO Auth version: 1.0.4
```
> feat: add commit hash to dev version

- commands/cloudapi-v6/ipfailover.go
- commands/cloudapi-v6/lan.go
- commands/cloudapi-v6/s3key.go
- commands/dbaas/postgres/cluster.go
In PR #191 UUID matching for ID fields was introduced. Lan ID and S3key ID fields however don't respect this, making --lan-id and --s3key  flags unusable. (Bug unreleased)
This PR fixes this bug
Release is blocked until this PR is merged
> fix: remove UUID validation lan, s3key

- snap/snapcraft.yaml
snap releases have stray character in output of version command: IONOS Cloud CLI version: v6.3.2'
```
~$ ionosctl version
IONOS Cloud CLI version: v6.3.2'
SDK GO version: 6.1.3
SDK GO DBaaS Postgres version: 1.0.4
SDK GO Auth version: 1.0.5
```
> fix: stray character in ionosctl version for snap

- commands/cloudapi-v6/label.go
- docs/subcommands/compute-engine/label-add.md
- docs/subcommands/compute-engine/label-get.md
- docs/subcommands/compute-engine/label-list.md
- docs/subcommands/compute-engine/label-remove.md
- pkg/core/command.go
- pkg/core/flag.go
limit flag value to values in specific set. Useful for image upload/patch/delete, label resource, etc.
labelResourceFlag type is now a SetFlag (more general)
> enhancement: limit flag value to values in specific set

- docs/README.md
IonosCTL CLI is currently under development. We are working on adding new commands and use-cases in order to support all the operations available in the Cloud API.
> TWT-296-ionosCTL update: Remove note from Introduction

- commands/cloudapi-v6/image.go
- docs/subcommands/compute-engine/image-upload.md
- pkg/utils/utils.go
Get uploaded images using a List & filter. For each uploaded image, run an image update on it
NOTES: https://jira.sso.ionos.cloud/browse/SDK-1163. Currently can't filter over a single key with multiple values (i.e. `image list` with filter `locations=fra,fkb,txl` is not possible yet).
Scenario - error is thrown: User uploads `kolibri.iso` to `fra` and `txl`. What if another image with same alias, `kolibri.iso` already exists at different location, `fkb`? The `diff`-finding `image list` would also register `kolibri.iso` at `fkb` as a newly uploaded image.    The solution is to limit the `diff`-finding `image list` to `location=fra,txl` (aka Filter by Location key with multiple values), however this is impossible right now until SDK-1163. As a temporary workaround, an error is thrown
> feat: update after image ftp upload

- commands/root.go
double `v` characters in kibana logs. `ionosctl/vv6.3.3_ionos-cloud-sdk-go/v6.1.3`
removed duplicated code (struct cliVersion)
> fix: two vees in version for CLIHttpUserAgent

- commands/dbaas/postgres/cluster.go
This fixes a mistake introduced in #191 , where the `cidr` flag for postgres was given the type UUID. CIDR is of the form `10.3.4.12/24`...
> fix: type of CIDR flag is string

- .gitignore
- commands/cloudapi-v6/completer/properties.go
- commands/cloudapi-v6/completer/properties_test.go
- commands/cloudapi-v6/k8s_nodepool.go
- commands/cloudapi-v6/server.go
It's fairly easy to misconfigure a server or k8s node pool by using a CPU family that is not available in the datacenter.
I've added a completer that fetches a datacenter if the corresponding flag was already provided and completes according to what is available.
When `--datacenter-id` is not specified, the default list is returned.
This should make interactive usage of `ionosctl` a bit less error prone.
> feat: Add dynamic completion for --cpu-family

- pkg/utils/wait.go
- pkg/utils/watch.go
ionosctl was checking for response from server every 10 nanoseconds consuming a lot of cpu resources. Now it waits one second.
> changed pollTime

- commands/dbaas/postgres/backup.go
- commands/dbaas/postgres/cluster.go
- pkg/core/command_runner.go
- pkg/core/flag.go
Similar to https://github.com/ionos-cloud/ionosctl/pull/220, I found another. Despite the name, the backupID is actually not a UUID, instead it looks like `7aaf0e1b-fdd0-11ec-b738-828eb1aea7fe-4oymiqu-13`.
> fix: Postgres backupid flag type

- commands/cloudapi-v6/resource.go
Fixes the issue that listing of group resources always returned an empty list. (max-results defaulted to 0)
> fix: listing of group resources

- pkg/printer/result.go
- pkg/printer/result_test.go
Using the default go representation of string slices is a bit cumbersome to process on the command line.
The text output of read commands should be valid input for writing and `[a, b]` is not a valid string slice input.
Consider the following scenario that this change makes possible (ID flags omitted for brevity):
```sh
ionosctl nic update --ips "$(ionosctl nic get --cols Ips --no-headers | cut -d, -f1)"
```
> feat: Improve string slice printing

- commands/certmanager/certificates.go
- commands/certmanager/delete.go
- commands/certmanager/get.go
- commands/certmanager/patch.go
- pkg/utils/utils.go
Added completions for "ID" flag for some certmanager commands
Updated "Map" util function to Go 1.17 standards using generics
> fix: completions for cert manager

- commands/cloudapi-v6/applicationloadbalancer_rule_httprule.go
- commands/cloudapi-v6/cpu.go
- commands/cloudapi-v6/ipconsumer.go
- commands/cloudapi-v6/ipfailover.go
- commands/cloudapi-v6/k8s_nodepool_lan.go
- commands/cloudapi-v6/networkloadbalancer_rule_target.go
- commands/cloudapi-v6/query/query_params.go
- commands/cloudapi-v6/resource.go
- commands/cloudapi-v6/s3key.go
- internal/pointer/pointer.go
- services/cloudapi-v6/constants.go
- services/cloudapi-v6/resources/query_params.go
- services/cloudapi-v6/resources/query_params_test.go
Add MaxResults to all list commands where it was missing from 
Safeguard that setting MaxResults to 0, or OrderBy to "" would never send these values to the API -- both by using the Setter functions to avoid setting those values, and also by using pflag's `Changed()` function (which returns true only if the flag is set)
**NOTE**: The cloudapi query parameters would no longer be duplicated if we add a `compute` namespace for CloudAPI resources, as we could add them to `GlobalFlags()` of the `compute` namespace.
> fix: max results

- CHANGELOG.md
- commands/version.go
Makes the version command behave predictably, like that of any other CLI:
```bash
$ npm -v
8.3.1
$ python3 --version
Python 3.10.6
$ javac --version
javac 11.0.17
```
etc...
Before:
```bash
$ ionosctl version
IONOS Cloud CLI version: v6.5.0
SDK GO version: 6.1.3
SDK GO DBaaS Postgres version: 1.0.4
SDK GO Auth version: 1.0.5
```
After:
```bash
$ ionosctl version
v6.5.0
```
```bash
$ ionosctl version -v
v6.5.0
[INFO] sdk-go 6.1.3
[INFO] sdk-go-dbaas-postgres 1.0.4
[INFO] sdk-go-dbaas-auth 1.0.5
[INFO] sdk-go-cert-manager v1.0.0
```
> fix: version command 

- internal/confirm/confirm.go
- internal/confirm/confirm_test.go
- pkg/utils/confirmation.go
the current way of asking for confirmation is pretty verbose and is hard to integrate with the `--force` flag. this provides an easy to use interface for one-line confirm asking
> refactor: add ask pkg

- commands/cloudapi-v6/user.go
Group User List was made with depth of 0 since flag wasn't set. 
- Added missing flags to Group User List command
- Fixed viper binding confusion for `--cols` between `group user list` and `user list`: One was bound to `c.NS` while other was bound to `c.Resource`
> fix: Group User list

- commands/cloudapi-v6/query/query_params.go
- commands/cloudapi-v6/volume_test.go
- pkg/printer/result.go
Changed filters and cols to be case insensitive since one was expecting Title case, and one was expecting full lowercase.
```
% ionosctl server list --all -F namE=dp --cols NAME,TyPe,availabilityZOne --no-headers 
dp-fa0368d9625a36ba65b3-gw4jgwdcnz   ENTERPRISE   AUTO
```
> changed: cols, filters are now case insensitive

- commands/cloudapi-v6/examples.go
- docs/subcommands/application-load-balancer/applicationloadbalancer-flowlog-create.md
- docs/subcommands/application-load-balancer/targetgroup-target-add.md
- docs/subcommands/application-load-balancer/targetgroup-target-remove.md
- docs/subcommands/compute-engine/container-registry-registry-create.md
- docs/subcommands/compute-engine/container-registry-repository.md
- docs/subcommands/compute-engine/image-upload.md
- docs/subcommands/networkloadbalancer/networkloadbalancer-rule-target-add.md
- docs/subcommands/networkloadbalancer/networkloadbalancer-rule-target-remove.md
Some flags were wrong, possibly renamed after the example was written.
Most of our examples are non-docopt compliant, and maintaining them is unfeasible. We need to generate these automatically at some point.
#261
> fix #261: alb, targetgroup examples

- .github/workflows/build.yml
- .github/workflows/ci.yml
- Makefile
- commands/container-registry/registry/list.go
- commands/container-registry/registry/registry_integration_test.go
- commands/container-registry/token/token_integration_test.go
- commands/dbaas/mongo/cluster/create.go
- commands/dbaas/mongo/mongo_integration_test.go
temporarily skip container registry tests because 409 Conflict
Mongo CIDRs used for tests  will be generated in a tighter (more controlled) subnet: `192.168.1.129/24` - `192.168.1.254/24`
Container Registry names used for tests  will follow this format: `ionosctl-crreg-test-{8 random alphanum chars}`
Run only 2 CIs instead of 4 (Windows, Ubuntu, instead of Windows, Ubuntu, MacOS and Build <Ubuntu>)
> test: fix flaky integration tests

- commands/auth-v1/token.go
- commands/auth-v1/token_test.go
- commands/cloudapi-v6/applicationloadbalancer_rule_httprule.go
- commands/cloudapi-v6/applicationloadbalancer_rule_httprule_test.go
- commands/cloudapi-v6/contract_test.go
- docs/subcommands/Authentication/token.md
- pkg/printer/result.go
Add ability to print all columns using `all`, eg `ionosctl dc ls --cols all`
refactored: some resources weren't using `printer.GetHeaders` and were still tightly coupled to their own column making func
> feat: add ability to print all cols

- commands/cloudapi-v6/k8s_nodepool_lan.go
- commands/dataplatform/cluster/kubeconfig.go
- commands/dataplatform/cluster/update.go
Copy the address of the loop variable before assigning it
Before:
```
% ionosctl k8s np lan add ... --network 80.120.160.240/24,40.80.120.160/24 --gateway-ip 1.2.3.4,1.2.3.6 --lan-id 4 
LanId   Dhcp   RoutesNetwork                       RoutesGatewayIp
4       true   40.80.120.160/24,40.80.120.160/24   1.2.3.4,1.2.3.6
```
After:
```
% ionosctl k8s np lan add ...
LanId   Dhcp   RoutesNetwork                        RoutesGatewayIp
1       true   80.120.160.240/24,40.80.120.160/24   1.2.3.4,1.2.3.6
```
> fix #289: ionosctl k8s np lan add using only last network

- commands/dataplatform/nodepool/delete.go
If `--nodepool-id` is empty, throw an error in prerun for `ionosctl dp np delete`
improve ask for confirmation, add names for the nodepool
> fix: fix nodepool ID prereq in dp nodepool delete

- commands/dns/dns.go
- commands/root.go
- docs/subcommands/DNS/record/create.md
- docs/subcommands/DNS/record/delete.md
- docs/subcommands/DNS/record/get.md
- docs/subcommands/DNS/record/list.md
- docs/subcommands/DNS/record/update.md
- docs/subcommands/DNS/zone/create.md
- docs/subcommands/DNS/zone/delete.md
- docs/subcommands/DNS/zone/get.md
- docs/subcommands/DNS/zone/list.md
- docs/subcommands/DNS/zone/update.md
- internal/client/client.go
Currently, in #287, you aren't able to change the api-url flag, and always the host-url is hardcoded to be `dns.de-fra.ionos.com`, while the help text shows that the default is actually `api.ionos.com`.
This PR implements a workaround to manually set the flag to the desired default, if the flag hasn't changed (is unset), and fixes the discrepancy of the help text and the actually used default value
> fix: DNS API hostUrl workaround

- commands/cloudapi-v6/completer/filters.go
- docs/subcommands/Compute Engine/request/list.md
Some filters for Requests weren't available. The way the current implementation works, is that we manually add each resource's available filters by iterating through the SDK struct properties and adding them as available filters
The fix in this PR adds the nested object `RequestStatusMetadata`
> fix: manually add properties of nested RequestStatusMetadata to RequestsFilters

- commands/cloudapi-v6/query/query_params.go
Fixes #310 - keys being set to lowercase, and as such, filters for keys such as `imageType` don't work, CLI sends `imagetype` to API  
Hacky fix, we manually overwrite the `--filters` values to change keys to those expected by API (by using `availableFilters`). for some reason, `getFilters` doesn't have access to `availableFilters`
The optimal fix would have been to  add `availableFilters` as an argument to `getFilters`, but this would involve touching code in every single command that uses filters /  refactoring this file: https://github.com/ionos-cloud/ionosctl/blob/master/commands/cloudapi-v6/completer/filters.go - both would take a lot of work.
in any case, this PR simply hides the technical debt a bit better rather than being a permanent fix - now it is implied that …
> fix #310: camelcase filters key bug

- commands/cloudapi-v6/server.go
- commands/cloudapi-v6/server_test.go
In the past, all CUBE servers had to have "INTEL_SKYLAKE" as a CPU Family. As such, INTEL_SKYLAKE was hardcoded as the CpuFamily field. something changed on the API side, and API started throwing errs if Cpu Family was set: `[VDC-5-1921] The attribute 'cpuFamily' must not be provided for Cube servers.`
This PR removes the hardcoded value, now this field will be nil if the flag is not set - but still allows the user to modify this field, in case the API returns to its old state in the future
> fix: remove hardcoded INTEL_SKYLAKE for creating cubes

- commands/dataplatform/cluster/create.go
- docs/subcommands/Managed-Stackable-Data-Platform/cluster/create.md
seems like 22.11 is no longer supported. 
```
Error: 422 Unprocessable Entity: {"httpStatus":422,"messages":[{"errorCode":"dsaas-o-422","message":"request not possible because: the version '22.11' is not available anymore"}]}
```
also, setting field to nil results in API choosing a bad version anyway:
```
Error: 422 Unprocessable Entity: {"httpStatus":422,"messages":[{"errorCode":"dsaas-o-691","message":"version 1.1.0 is not a valid version from '22.06, 22.09, 22.11, 23.4'"}]}
```
so this PR explicitly sets 23.4 as a default
> fix: change dataplatform cluster default version to 23.4

- CHANGELOG.md
- commands/dns/record/record.go
- commands/dns/zone/zone.go
Fixes a bug in which DNS completions wouldn't work if the server URL is set to `api.ionos.com`. Seems like our dns-level flag default for `api-url` doesn't get set if calling completions from this namespace
> fix: completions for DNS if api url set to api.ionos.com

- pkg/printer/printer.go
- pkg/printer/printer_test.go
The CLI rewraps any output that's not a `Result` in a dummy struct for marshalling.
As a user, I would expect `-o json` to be the "raw" version of the response from the server, i.e. without omitting or adding any extra fields.
Adding some indent is fine, since it's a CLI which is likely used by humans.
Consider this example to get the newest available k8s version:
```
curl ... https://api.ionos.com/cloudapi/v6/k8s/versions | jq -r '. | first'
ionosctl k8s version list -o json | jq -r '.Message | first'
```
It can be somewhat confusing for new users of `ionosctl` if the output differs in such a slight way.
This is somewhat related to https://github.com/ionos-cloud/ionosctl/issues/249, but I have no issues with the `items` approach that was implemented.
> fix: Don't rewrap JSON output

- commands/dataplatform/cluster/create.go
- docs/subcommands/Database-as-a-Service/mongo/cluster/create.md
- docs/subcommands/Managed-Stackable-Data-Platform/cluster/create.md
version 23.4 is no longer available
```
Error: 422 Unprocessable Entity: {"httpStatus":422,"messages":[{"errorCode":"dsaas-o-422","message":"request not possible because: the version '23.4' is not available anymore"}]}
```
also, setting field to nil still results in API choosing a bad version anyway:
```
Error: 422 Unprocessable Entity: {"httpStatus":422,"messages":[{"errorCode":"dsaas-o-691","message":"version 1.1.0 is not a valid version from '22.06, 22.09, 22.11, 23.4, 23.7'"}]}
```
so this PR explicitly sets 23.7 as a default
> fix: change dataplatform default version to 23.7

- commands/dns/dns.go
- commands/root.go
- internal/client/client.go
- pkg/config/config.go
- pkg/config/config_test.go
- pkg/constants/constants.go
fixes #349: `IONOS_API_URL` being overriden by default flag values
> fix #349: api url env var

- commands/cloudapi-v6/image.go
- pkg/constants/constants.go
Fixes #359. `image update` shouldn't look at values of unset flags.
This PR uses `pflag.Visit` and `pflag.VisitAll`. In the case of `image upload`, we actually want the unset flags to act as default values for the image, and as such, in this case we use `VisitAll`.
> fix #359: image patch 

- commands/cloudapi-v6/request.go
It is confusing for the user why the status column is missing. If the user is unaware of the existance of `--depth` flag he might not understand why these columns are blank.
Before:
```
% i request list -M 1
RequestId                              CreatedDate                     Method   Status   Message   Targets
aa723d65-f963-46ec-9685-0481af014ede   2023-09-13 15:18:42 +0000 UTC   POST                        
```
After:
```
% i request list -M 1
RequestId                              CreatedDate                     Method   Status   Message                                  Targets
aa723d65-f963-46ec-9685-0481af014ede   2023-09-13 15:18:42 +0000 UTC   POST     DONE     Request has been successfully executed   datacenter, ,6308abd0-443f-4980-bc24-8c977e737b76, 
```
> fix: default depth of 2 for requests list

- commands/dataplatform/dataplatform_integration_test.go
fixes various issues with the dataplatform tests
- Add a missing call for nodepool test
- Add missing check for setup error
- Remove a debug print 
- Add more explicit messages in case of failed asserts
- Increase sleep time for test teardown
> test: Fix dataplatform tests

- .github/workflows/ci.yml
Changes  Windows CI to run only the unit test suite. Ubuntu still runs all tests.
Running two concurrent integration test suites is a waste of resources considering that there is no difference in OS behaviour for these tests.
> enhancement: CI run integration tests only on Ubuntu

- .github/workflows/docs.yml
If  the `Docs` workflow detects differences in the generated documentation, the call-to-action message should tell the user to run `make docs`. However in the past this would actually cause this directive to run, and the output would be something like:
Before:
```
There are differences in the generated documentation. Run --- Purging docs ---
rm -rf docs/subcommands
touch docs/summary.md
rm docs/summary.md
--- Regenerating docs --- to fix.
```
After:
```
There are differences in the generated documentation. Run 'make docs' to fix.
```
> fix: If diff in generated docs, display 'make docs' rather than actually running this directive

- commands/dataplatform/dataplatform_integration_test.go
Remove goroutine for dataplatform tests which would lead to data races
> test: remove goroutine identify not set

- commands/cfg/cfg.go
- commands/cfg/cfg_test.go
- commands/cfg/whoami.go
- commands/dns/dns_integration_test.go
- commands/root.go
- docs/subcommands/Compute Engine/config/whoami.md
- docs/summary.md
- internal/client/client.go
- internal/client/model.go
- pkg/config/config.go
- pkg/config/config_test.go
- pkg/constants/constants.go
Introduces a command for debugging authentication:
Valid credentials - Username is printed. In case of Token auth, the JWT is parsed and Users API used to find the username.
```
% i cfg whoami   
alex[...]@[...].com
```
No credentials provided:
```
% i whoami    
Note: Authentication failed! None of the authentication layers had a token, or both username & password set.
Authentication layers, in order of priority:
[1] Global Flags (--token)
[2] Environment Variables (IONOS_TOKEN, IONOS_USERNAME, IONOS_PASSWORD)
[3] Config file settings (userdata.token, userdata.name, userdata.password)
```
Invalid credentials - shows used layer and whether using token or username & password:
```
% i whoami
Note: Authentication failed!
Authentication layers, in order of priority:
[1] Global Flags (--token) …
```
> feat: whoami

- Makefile
Generating mocks with an out of date `mockgen` tool would result in lots of unreadable errors/panics seemingly originated from go's std lib. I added this notice so that you don't need to dig through scripts/tools to rule out possibly responsible faults.
> chore: [no ci] add mockgen notice to Makefile 

- CHANGELOG.md
- commands/cloudapi-v6/firewallrule.go
Fixes two issues with `firewallrule delete`:
1. `--firewallrule-id` was not required, resulting in a 405 if not set (`DELETE` not allowed) - since the endpoint missed the ID if unset
2. The IDs were not properly extracted from the flags, resulting in a 404 - since the endpoint missed all IDs whether set by the user ot not
> fix: delete firewallrules 404, 405

- commands/dataplatform/dataplatform_integration_test.go
Got another 403 Forbidden: https://github.com/ionos-cloud/ionosctl/actions/runs/6419968552/job/17430993332#step:5:28
For some reason, although we used the same datacenter ID in the FindByID as the one returned in the `setup`, it got a 404.
This PR makes the setup wait 15 seconds after creation, maybe this can fix it.
Fatalf logs return more info now.
> test: further debugging 403 Forbidden

- CHANGELOG.md
- commands/cloudapi-v6/server.go
- commands/cloudapi-v6/server_test.go
- commands/cloudapi-v6/volume.go
- commands/cloudapi-v6/volume_test.go
Using private images for `volume create` is impossible since `ionosctl` forces the user to set `--sshkey-path` or `--password` for all types of images. However, the API expects these to not be set if using private images.
This PR changes the prerun to take private HDD images into account for `volume create`
> fix: password, sshkey-path not required for private images

- CHANGELOG.md
- commands/cloudapi-v6/cdrom.go
- commands/cloudapi-v6/completer/custom_ids.go
- commands/cloudapi-v6/completer/ids.go
- commands/cloudapi-v6/image.go
- commands/cloudapi-v6/server.go
- commands/cloudapi-v6/server_test.go
- commands/cloudapi-v6/volume.go
- commands/cloudapi-v6/volume_test.go
Add completer descriptions for `--image-id` flag.
Completed images are now relevant (i.e. only HDD images from the same location as the selected datacenter are completed for `volume create --image-id`).
Completed images will also be ordered so that private (user-uploaded) images are shown first.
```
% i volume create --datacenter-id 5b155c2a-a580-41fe-8fd3-6c0562889d04 --image-id  <TAB>
Completing completions
2c27b1a4-4d5d-11ee-a519-1ed9fe6a7252  --  LINUX HDD public [rocky:latest,rocky:9] (rocky-9.2-genericcloud-20230513) from fr/par
2eefbc0c-5f7c-11ed-9aa6-0e69f8b5a652  --  LINUX HDD public [ubuntu:20.04] (ubuntu-20.04-server-cloudimg-amd64-20220824) from fr/par
2f6abdf0-d9c6-11ed-b4c9-46b39ba06ae6  --  LINUX HDD public [alma:9,alma:latest] (almalinux-9-GenericCloud-20221118) from …
```
> enhancement: image id completer descriptions

- CHANGELOG.md
- commands/cloudapi-v6/examples.go
- commands/cloudapi-v6/lan.go
- commands/cloudapi-v6/pcc.go
- docs/subcommands/Compute Engine/lan/create.md
- docs/subcommands/Compute Engine/lan/update.md
- docs/subcommands/Compute Engine/pcc/create.md
- docs/subcommands/Compute Engine/pcc/delete.md
- docs/subcommands/Compute Engine/pcc/get.md
- docs/subcommands/Compute Engine/pcc/list.md
- docs/subcommands/Compute Engine/pcc/peers/list.md
- docs/subcommands/Compute Engine/pcc/update.md
- services/cloudapi-v6/constants.go
Rename Private Cross Connect to Cross Connect and adds an alias of `cc` to the `pcc` command
> doc: rename Private Cross Connect to Cross Connect

- CHANGELOG.md
- commands/cloudapi-v6/backupunit.go
Fixes ` backupunit list` missing columns and `get-sso-url` `%` elements being treated as placeholder strings
i.e.
```
{
"ssoUrl" : "https://backup.ionos.com/api/2/idp/external-login#ott=T1RUAQAAAH76SwAAAAAAaK8qvEA1TyeIFlqYI1z-VQ%3D%3D&targetURI=https://backup.ionos.com/bc"
}
```
would be converted to
```
BackupUnitSsoUrl
https://backup.ionos.com/api/2/idp/external-login#ott=T1RUAQAAAH76SwAAAAAAaK8qvEA1TyeIFlqYI1z-VQ%!D(MISSING)%!D(MISSING)&targetURI=https://backup.ionos.com/bc
```
> fix: backupunit prints

- internal/core/command_runner.go
- internal/core/flag.go
Fixes prerun check failing even though `--json-properties` is set. Would fail only for certain commands
> fix: allow prerun checks to succeed if pflag detects changes in the verified flag

- commands/cloudapi-v6/image.go
- commands/cloudapi-v6/image_test.go
- commands/cloudapi-v6/request.go
- commands/cloudapi-v6/request_test.go
Fixes #406: Getting no results for images, requests should return a zero status code.
> fix #406: empty result should return a zero status code

- CHANGELOG.md
- commands/cloudapi-v6/image.go
- docs/subcommands/Compute Engine/image/upload.md
- go.mod
- internal/core/command_builder.go
- pkg/functional/types.go
- services/cloudapi-v6/resources/image.go
This PR improves `image upload` command help text & errors.
Decouples `ImageUpload` of the API-related `ImageService`
Deprecated `--image-alias`:
- Added `--rename`.  Setting it will result in `--image-alias` being set.
-  Hidden `--image-alias`.
- Added `PreRunWithDeprecatedFlags` and `functional.Tuple` for easily marking  deprecated flags in the future
> feat: image upload improvements

- snap/snapcraft.yaml
- tools/build.sh
Updates `snapcraft.yml` to use core20 (Ubuntu 20.04).
I decided not to update to core22 because of [this issue](https://forum.snapcraft.io/t/snapcraft-network-error-seemingly-with-all-core22/34588) which I couldn't easily work around
> enhancement: snap core20

- CHANGELOG.md
- commands/cloudapi-v6/k8s_nodepool.go
- docs/subcommands/Managed-Kubernetes/nodepool/update.md
Fix disabling autoscaling on a Kubernetes node pool. Autoscaling is disabled when the min and max counts are `null`.
Previously this resulted in this error:
```
Error: 422 Unprocessable Entity {
"httpStatus" : 422,
"messages" : [ {
"errorCode" : "110",
"message" : "[(root).properties.autoScaling.minNodeCount] Attribute has to be greater than 0"
} ]
}
```
> fix: Allow disabling node pool autoscaling

- .gitignore
- CHANGELOG.md
- commands/root.go
Reorders the Help Template such that current command related  functionalities are printed last, similar to how `kubectl` does it. Basically in CLIs the read order is bottom-to-top, so this new order should reflect that.
This should get rid of the "ping-pong" style scrolling that users have to do to find information for that command (i.e. scrolling up to examples, down to flags, up to usage, etc.). This was also most noticeable in commands with available subcommands, where users commonly had to scroll up to see these subcommands.
Also, now a developer can just re-order the templates more easily, they don't depend on each other for newlines, indents, trims, etc. and manage the whitespaces around them by themself, as well as the if-conditions are reworked to be included in that specific …
> enhancement: restructure help template

- CHANGELOG.md
- commands/root.go
- commands/shell.go
- internal/version/version.go
- internal/version/version_test.go
- tools/build.sh
Moves versioning logic to a new `version` pkg.
Use `buildinfo` to get version, since this is empty if installed via `go install`.
```
% go install github.com/ionos-cloud/ionosctl/v6@(some-commit)
go: downloading github.com/ionos-cloud/ionosctl/v6 v...
% ionosctl version
DEV-
```
```
% go install github.com/ionos-cloud/ionosctl/v6@67c7f98                                     
go: downloading github.com/ionos-cloud/ionosctl/v6 v6.7.5-0.20240301130018-67c7f986faf0
% i version
DEV-67c7f98
```
```
% i version
DEV-67c7f98
```
> fix: version if installed via 'go install'

- .github/workflows/release.yml
- .gitignore
- .goreleaser.yml
Relese binaries had the version `unknown` because the ldflags were not set correctly.
The Github action also printed out some deprecation warnings.
> fix: goreleaser builds

- CHANGELOG.md
- commands/cloudapi-v6/image.go
Fixes a bug for `image upload` where using a custom `--ftp-url` and no `--location` would silently fail the operation
> fix: image upload silent fail

- commands/dbaas/mariadb/cluster/create.go
- commands/dbaas/mongo/cluster/create.go
- commands/dbaas/mongo/cluster/update.go
- docs/subcommands/Database-as-a-Service/mariadb/cluster/create.md
- docs/subcommands/Database-as-a-Service/mongo/cluster/create.md
- docs/subcommands/Database-as-a-Service/mongo/cluster/update.md
Removes `--wait-for-request` as this does nothing. We can't implement this 'as is' because CloudAPI Requests API does not register these requests.
Hides `--wait-for-request` for mongo commands for the same reason, but do not remove it as this might be used by users in scripts (and removing it outright would cause 'unknown flag: -w'
Fixes completions for `--version` flag
Fixes misspelled 'Satuday' -> 'Saturday' for maintenance day completions
> fix: version flag completions, remove '-w' for maria, hide '-w' for mongo

- Makefile
- commands/logging-service/pipeline/create.go
- commands/logging-service/pipeline/pipeline.go
Disabled logging-service tests and fixed the `--json-properties` flag check.
> Fix: logging service tests

- CHANGELOG.md
- commands/cloudapi-v6/nic.go
- test/bats/cloudapi/volume.bats
- test/bats/setup.bats
Adds a BATS test suite for testing volume interactions with backupunits, servers, etc
Fixed a bug with NIC not creating the LAN when missing - returning a 404, and added a test case for this
> test: add BATS server volume test

- commands/cfg/login.go
I saw a workflow that failed with the following error message:
```
Error: failed retrieving current tokens: %!w(<nil>)
```
This is because the error wasn't wrapped correctly.
> fix: Fix error message on failed tokens API call

- CHANGELOG.md
- commands/cloudapi-v6/image.go
- docs/subcommands/Compute Engine/image/upload.md
> fix: image upload docs

- CHANGELOG.md
- commands/cloudapi-v6/k8s_nodepool.go
- internal/core/command_runner.go
- test/bats/cloudapi/k8s.bats
`json-properties` flag not working on k8s nodepool as reported in https://github.com/ionos-cloud/ionosctl/issues/463. 
Fixed by removing Viper binding for it and `json-properties-example`.
> fix: json-properties flag not working on k8s nodepool

- Makefile
- commands/cfg/cfg_test.go
- commands/dns/dns_integration_test.go
- commands/token/token_integration_test.go
- internal/utils/utils.go
Don't error out on [UTC] suffix removal in our tests, as now the API sometimes returns a valid RFC3339 string
It is possible that old objects retain [UTC] suffix while new ones don't have the suffix.
I've also modified the Makefile to make it easier to run tests locally while skipping the bats tests.
> test: fix intermittent UTC suffix failure

- CHANGELOG.md
- commands/cloudapi-v6/server.go
- commands/cloudapi-v6/volume.go
- test/bats/cloudapi/snapshot.bats
- test/bats/cloudapi/volume.bats
Allow usage of snapshots for --image-id flag on volume and CUBE creation.
Adds a step to the BATS Volume test to test this scenario
> Fix: allow usage of snapshots for volumes as --image-id

- CHANGELOG.md
- commands/cloudapi-v6/backupunit.go
- commands/cloudapi-v6/backupunit_test.go
- docs/subcommands/Managed-Backup/create.md
- docs/subcommands/Managed-Backup/delete.md
- docs/subcommands/Managed-Backup/update.md
- test/bats/cloudapi/volume.bats
Backupunit resources are not tracked on `/requests` endpoint leading to a 404 if -w is  set
Hide `-w` flag and remove its behaviour, but keep it for backward compatibility - this means we won't throw errors if `-w` is set, but setting it will do nothing
> fix: 404 on backupunit wait

- test/run.sh
Add `docs` to list of directories that do not trigger BATS tests if modified
> test: dont run BATS tests if modified files in docs dir

- CHANGELOG.md
- commands/cfg/login.go
Changes the login message to include the username you have logged in as, if possible.
Logging in will now still succeed if we cannot retrieve the number of tokens, but instead we will simply not print this information if we fail to retrieve it.
New:
```
% i login --user $IONOS_USERNAME --password $IONOS_PASSWORD
Config file [...]/config.json already exists. Do you want to replace it? [y/n]: y
Note:                                    (note: not printed if both of the next two notes are empty)
• Logged in as [...]                    (note: not printed if there is an error getting the username)
• Your account has 8 active tokens.     (note: not printed if there is an error getting the number of tokens)
Config file updated successfully. Created the following fields in your config file:
• …
```
> enhancement: logged in as

- CHANGELOG.md
- go.mod
- go.sum
- vendor/github.com/dustin/go-humanize/comma.go
- vendor/github.com/dustin/go-humanize/ftoa.go
- vendor/github.com/dustin/go-humanize/si.go
- vendor/modules.txt
Due to CVE concerns we are bumping the minimum required Go version to build ionosctl to 1.23.8
> deps: bump min go version to 1.23.8

- commands/dbaas/mongo/cluster/create.go
- commands/dbaas/mongo/cluster/update.go
- commands/dbaas/mongo/completer/ids.go
- docs/subcommands/Database-as-a-Service/mongo/cluster/create.md
- docs/subcommands/Database-as-a-Service/mongo/cluster/update.md
This adds the `--version` parameter to the `ionosctl dbaas mongo cluster update` command which allows to upgrade the MongoDB version used by a cluster. It also pulls the available MongoDB versions for completions.
This also increases the default version for new MongoDB clusters (from "6.0" to "7.0", since the former is close to EOL)
> feat: allow mongodb version to be updated

- CHANGELOG.md
- commands/cfg/location.go
- internal/client/client.go
- internal/client/config_integration.go
- internal/client/config_integration_test.go
Refactor to use ConfigSource return type
After switching to the func-approach, the funcs were confounding "not found" errors and "incorrect config contents" errors which caused the bug. This is now fixed
Add tests covering each resolution path.
> fix: fallback to IONOS_CONFIG_FILE if not found at --config location

- commands/dbaas/mongo/cluster/update.go
- docs/subcommands/Database-as-a-Service/mongo/cluster/update.md
This adds a `LongDesc` to the `ionosctl dbaas mongo update` command. This is focused to make it easier to understand what you can or can't patch for which kind of cluster you might have.
> doc: Correct and enhance documentation for mongodb cluster updates

- commands/cloudapi-v6/image/upload.go
Adds better debugging for `-v` flag when using `ionosctl image upload`. Change logic for warning about invalid locations and warn about the old `fra, fkb` style too (although they are still supported)
> enhancement: improve image upload verbose prints

- test/bats/apigateway/apigateway.bats
- Fix API error when updating API Gateway. 
- Replaced --logs true in "run ionosctl apigateway gateway update --gateway-id "$gateway_id" --logs true -o json 2> /dev/null" because it caused the following error: 
"Error: 422 Unprocessable Entity: {"httpStatus":422,"messages":[{"errorCode":"Validation","message":"in order to enable the logs you need to enable the central logging first"}]}"
> fix: change test parameter

- commands/container-registry/registry/post.go
- docs/subcommands/Container-Registry/registry/create.md
Adds `-l` shorthand and improves help text for `container-registry registry create`
> fix: add '-l' shorthand for '--location' for registry create

- commands/cloudapi-v6/image/upload.go
- docs/subcommands/Compute Engine/image/upload.md
Improve 'image upload' docs
Remove mentions of 'kolibri.iso'
Fix paragraphs displaying within list items on Gitbook instead of spaced properly.
Merge 'Examples' into the Long Help for a better formatting and to keep the bottom of the helptext more clean for the CLI users 
Change mentions of old location style to new location style: `fra` -> `de/fra`
Change default timeout of 300s to 1200s.
Add mention of 'ionosctl whoami --provenance' for debugging if IONOS_USERNAME and IONOS_PASSWORD are used
New help text
```
❯ i image upload --help
This command uploads one or more disk images to an FTP server using FTP over TLS (FTPS), then optionally updates the uploaded images via the Images API to set properties you passed as flags.
This command requires that you are logged in using IONOS_USERNAME …
```
> doc: improve image upload docs
