- commands/datacenter.go
- commands/lan.go
- commands/loadbalancer.go
- commands/location.go
- commands/login.go
- commands/nic.go
- commands/request.go
- commands/server.go
- commands/volume.go
- pkg/builder/command.go
- pkg/config/config.go
- pkg/config/config_test.go
- pkg/config/constants.go
- pkg/resources/client.go
- pkg/resources/client_test.go
- pkg/testdata/config.json
This should be possible.
I can add another prompt to the login command for the token if needed.
> Support bearer token auth

- go.mod
- go.sum
- pkg/resources/k8s.go
- vendor/github.com/ionos-cloud/sdk-go/v5/DOCS.md
- vendor/github.com/ionos-cloud/sdk-go/v5/api_kubernetes.go
- vendor/modules.txt
Update to sdk-go v5.0.3 - fix typo `K8sFindBySClusterId`
> Fix: update to sdk-go v5.0.3

- .github/workflows/build.yml
- .github/workflows/ci.yml
Description: 
* Update CI & Sonar workflows
> Fix: workflows for v6

- commands/datacenter.go
- commands/firewallrule.go
- commands/ipblock.go
- commands/lan.go
- commands/loadbalancer.go
- commands/nic.go
- commands/pcc.go
- commands/server.go
- commands/volume.go
- docs/subcommands/datacenter-create.md
- docs/subcommands/firewallrule-create.md
- docs/subcommands/ipblock-create.md
- docs/subcommands/lan-create.md
- docs/subcommands/loadbalancer-create.md
- docs/subcommands/nic-create.md
- docs/subcommands/pcc-create.md
- docs/subcommands/server-create.md
- docs/subcommands/volume-create.md
Description: 
* Add default name for resources: Datacenter, Server, Volume, Firewall Rule
> Feat: add default value for name option

- commands/examples.go
- commands/k8s_nodepool.go
- commands/k8s_nodepool_test.go
- commands/request.go
- docs/subcommands/k8s-nodepool-create.md
- docs/subcommands/k8s-nodepool-delete.md
- docs/subcommands/k8s-nodepool-get.md
- docs/subcommands/k8s-nodepool-list.md
- docs/subcommands/k8s-nodepool-update.md
- docs/subcommands/request-list.md
- pkg/config/constants.go
- pkg/core/command.go
Description: 
* Update storage size for nodepool cmd
* Update nodepool cmd to be able to set multiple LANs to a nodepool
> Fix: k8s nodepool cmd

- commands/cdrom_test.go
- commands/image.go
- commands/image_test.go
- docs/subcommands/image-get.md
- docs/subcommands/image-list.md
- docs/subcommands/server-cdrom-attach.md
- docs/subcommands/server-cdrom-detach.md
- docs/subcommands/server-cdrom-get.md
- docs/subcommands/server-cdrom-list.md
- pkg/config/constants.go
Description: 
* Add options to sort Images on `ionosctl images list` command based on Image Alias or part of Image Alias, or based by the time the Image was created.
> Feat: sort images based on ImageAlias, CreatedDate [v5]

- commands/examples.go
- commands/image_test.go
- commands/request.go
- commands/request_test.go
- commands/resource.go
- docs/subcommands/request-get.md
- docs/subcommands/request-list.md
- docs/subcommands/request-wait.md
- pkg/config/constants.go
Description:
Add options to sort Requests on `ionosctl request list` command based on Request Method, or based by the time the Request was created.
> Feat: sort requests by CreatedDate, Method [v5]

- commands/request.go
- commands/request_test.go
- docs/subcommands/request-get.md
- docs/subcommands/request-list.md
- docs/subcommands/request-wait.md
ionosctl request now is showing which resources is impacting and theirs ids
> now request command is showing target datacenters and their ids

- README.md
- commands/backupunit.go
- commands/cdrom.go
- commands/datacenter.go
- commands/firewallrule.go
- commands/group.go
- commands/image.go
- commands/ipblock.go
- commands/k8s_cluster.go
- commands/k8s_node.go
- commands/k8s_nodepool.go
- commands/login.go
- docs/README.md
- pkg/config/config.go
- pkg/config/config_test.go
- pkg/config/constants.go
- pkg/core/command_runner.go
- pkg/testdata/config.json
> Store API URL in config file

- commands/lan.go
- commands/loadbalancer.go
- commands/location.go
- commands/nic.go
- commands/pcc.go
- commands/request.go
- commands/resource.go
- commands/s3key.go
- commands/server.go
- commands/share.go
- commands/snapshot.go
- commands/user.go
- commands/volume.go
Update `getIds` functions used for autocompletion to get the corresponding api-url.
> Fix: update autocompletion functions [v5]

- commands/flowlog.go
- commands/lan.go
- commands/loadbalancer.go
- commands/location.go
- commands/natgateway.go
- commands/natgateway_flowlog.go
- commands/natgateway_rule.go
- commands/networkloadbalancer.go
- commands/networkloadbalancer_flowlog.go
- commands/networkloadbalancer_rule.go
- commands/nic.go
- commands/pcc.go
- commands/request.go
- commands/resource.go
- commands/s3key.go
- commands/server.go
- commands/share.go
- commands/snapshot.go
- commands/template.go
- commands/user.go
- commands/volume.go
Update getIds functions used for autocompletion to get the corresponding api-url.
> Fix: update autocompletion functions [v6]

- commands/root.go
> Fix: ionosctl version 

- commands/cloudapi-v6/nic.go
Quick fix of the response of nic loadbalancer detachh all command
> fix:/reponse nic loadbalancer detach all operation

- README.md
- commands/cloudapi-v6/nic.go
- commands/cloudapi-v6/nic_test.go
- commands/cloudapi-v6/volume.go
- commands/cloudapi-v6/volume_test.go
Missed 2 commands in adding checks on PreRun functions.
> fix: check filters for `server volume list` cmd [v6]

- commands/root.go
- internal/config/constants.go
- services/auth-v1/resources/client.go
- services/auth-v1/services.go
- services/cloudapi-v5/resources/client.go
Add user agent for each client in CLI. The http user agent has the following format: 
`ionosctl/v<version>_<user-agent-sdk>`
for internal testing of the CLI it will be:
`ionosctl/DEV_<user-agent-sdk>`
> feat: add user agent [v5]

- commands/cloudapi-v5/user.go
- commands/cloudapi-v5/user_test.go
- docs/subcommands/user-create.md
- docs/subcommands/user-update.md
- go.mod
- go.sum
- vendor/github.com/ionos-cloud/sdk-go/v5/.gitignore
- vendor/github.com/ionos-cloud/sdk-go/v5/README.md
- vendor/github.com/ionos-cloud/sdk-go/v5/client.go
- vendor/github.com/ionos-cloud/sdk-go/v5/configuration.go
- vendor/github.com/ionos-cloud/sdk-go/v5/go.mod
- vendor/github.com/ionos-cloud/sdk-go/v5/model_kubernetes_node_pool_properties_for_put.go
- vendor/github.com/ionos-cloud/sdk-go/v5/model_user_properties_put.go
- vendor/modules.txt
> feat: update sdk go v5.1.11

- commands/cloudapi-v6/examples.go
- docs/subcommands/compute-engine/ipblock-create.md
> fix: example and doc for `ipblock create` parameters [v6]

- Makefile
- commands/cloudapi-v6/natgateway_flowlog_test.go
- commands/cloudapi-v6/networkloadbalancer_flowlog_test.go
- internal/core/command_runner.go
- internal/core/test.go
- internal/utils/utils.go
- services/auth-v1/resources/client_test.go
- tools/auth-v1/regenerate_mocks.sh
- tools/cloudapi-v6/regenerate_mocks.sh
- tools/dbaas-postgres/regenerate_mocks.sh
- tools/regenerate_mocks.sh
Adding `goimports` check and update to automate this in adding new files.
> feat: add goimports .mk target [v6]

- README.md
- docs/README.md
Update path in install instructions.
> doc: fix path in install instructions

- README.md
- docs/README.md
This PR adds more info about tests into README.md files.
> doc: update Testing section [README.md]

- CHANGELOG.md
- commands/version.go
- go.mod
- go.sum
- vendor/github.com/ionos-cloud/sdk-go-auth/client.go
- vendor/github.com/ionos-cloud/sdk-go-auth/configuration.go
- vendor/github.com/ionos-cloud/sdk-go-auth/utils.go
- vendor/modules.txt
This PR updates version cmd to print all SDKs versions. Plus, it updates dependency SDK Go Auth to latest version.
> feat: add `sdk-go-auth` to `version` command

- CHANGELOG.md
- README.md
- docs/README.md
> add doc to install ionosctl on linux

- commands/cloudapi-v6/image.go
- commands/cloudapi-v6/label.go
- docs/subcommands/compute-engine/image-delete.md
- docs/subcommands/compute-engine/image-update.md
- docs/subcommands/compute-engine/label-add.md
- docs/subcommands/compute-engine/label-get.md
- docs/subcommands/compute-engine/label-list.md
- docs/subcommands/compute-engine/label-remove.md
- pkg/core/command.go
- pkg/core/flag.go
- Added image Update command, uses Go SDK Image Patch route
- Added Image Delete command
- Added Delete --all option 
- Minor improvements to SetFlag: description of flag will dynamically show which values user can choose from. (As a consequence, descriptions of flags should NOT contain a dot at the end )
> Feat: image update, delete commands

- pkg/config/config.go
- pkg/config/config_test.go
- pkg/testdata/config_just_token.json
- pkg/testdata/config_user_pass.json
certain edge cases for reading config file would fatally stop the execution when instead should recover
> fix: config file non-fatal edge cases, tests

- CHANGELOG.md
> doc: 6.4.2 changelog

- commands/cloudapi-v6/completer/custom_ids.go
- commands/cloudapi-v6/completer/ids.go
- commands/cloudapi-v6/image.go
- commands/cloudapi-v6/query/query_params.go
- commands/cloudapi-v6/share.go
- commands/cloudapi-v6/volume_test.go
- pkg/core/flag.go
- services/cloudapi-v6/resources/group.go
> added MaxResults for Group Shares

- pkg/printer/printer.go
Fixes the issue that text warnings or send to stdout which makes it hard to parse the output in a script.
> fix: write text warnings to stderr

- README.md
- docs/README.md
Add IONOS_LOG_LEVEL with explanation to Readme files.
FIx broken link.
> doc: update Readme with IONOS_LOG_LEVEL description

- commands/certmanager/certificates.go
- commands/cloudapi-v6/image.go
- internal/functional/functional.go
- pkg/utils/utils.go
> refactor: functional pkg

- CHANGELOG.md
> doc: 6.5.2 changelog

- .github/workflows/ci.yml
wasnt running for PRs opened after last commit
> doc: update 'on' for ci.yml

- commands/container-registry/token/patch.go
- commands/container-registry/token/post.go
- commands/container-registry/token/put.go
- commands/container-registry/token/tokens.go
- docs/subcommands/Container-Registry/token/create.md
- docs/subcommands/Container-Registry/token/replace.md
- docs/subcommands/Container-Registry/token/update.md
> Check Container Registry Token

- commands/cloudapi-v6/k8s_nodepool_lan.go
> fix: cols for k8s np lan ls

- internal/client/client.go
improve err checking for missing credentials. could be related to #235 or #251
No config file:
```
Error: failed loading credentials: stat /home/avirtopeanu/.config/ionosctl/config.json: no such file or directory: Please export IONOS_TOKEN, or IONOS_USERNAME and IONOS_PASSWORD, or do ionosctl login to generate a config file
```
Wrong config file perms:
```
Error: failed loading credentials: config file /home/avirtopeanu/.config/ionosctl/config.json has wrong permissions: 777, should be 600: Please export IONOS_TOKEN, or IONOS_USERNAME and IONOS_PASSWORD, or do ionosctl login to generate a config file
```
Wrong credentials: (API Error - perhaps we can throw a custom error?)
```
Error: 401 Unauthorized {
"httpStatus" : 401,
"messages" : [ {
"errorCode" : "315",
"message" : "Unauthorized"
} …
```
> fix #288: improve client, config err checking

- internal/client/client.go
fixing a bug I introduced in #291
> test: infinitely hanging login cmd test

- CHANGELOG.md
- commands/cfg/config.go
- commands/cfg/location.go
- commands/cfg/login.go
- commands/cfg/login_logout_integration_test.go
- commands/cfg/logout.go
- commands/cfg/whoami.go
- commands/root.go
- docs/subcommands/CLI Setup/config/location.md
- docs/subcommands/CLI Setup/config/login.md
- docs/subcommands/CLI Setup/config/logout.md
- docs/subcommands/CLI Setup/config/whoami.md
- docs/subcommands/CLI Setup/whoami.md
- docs/summary.md
- internal/client/client.go
- internal/client/client_test.go
- internal/jwt/token.go
- pkg/constants/constants.go
- pkg/doc/doc.go
- services/auth-v1/resources/client_test.go
- services/cloudapi-v6/resources/label_test.go
1. Make it easy to find the source (env, config, flag, etc) of each of the credentials
2. Make it possible to find out who we're currently logged in as.
3. If using token, decode it to find user UUID and use the UM API to get the user.
> feat: ionosctl whoami

- README.md
- docs/README.md
> docs: add sunset date

- CHANGELOG.md
Fix a few things related to the changelog prior to new release
> doc: changelog

- .github/workflows/release.yml
- Makefile
Have the ability to disable running tests on CD
> chore: optionally disable tests on cd and mute mongo tests

- .github/workflows/build.yml
- .github/workflows/docs.yml
Splits the "Build" workflow and the "doc diff checker" into separate workflows
> chore: split build and doc diff checker workflows

- commands/dbaas/mongo/cluster/cluster.go
- commands/dbaas/mongo/logs/logs.go
- commands/dbaas/mongo/snapshot/snapshot.go
- commands/dbaas/mongo/templates/templates.go
- commands/dbaas/mongo/user/user.go
will prevent panics in the future SDK release which returns some fields as nil
> fix: mongo nil dereferences

- commands/cloudapi-v6/snapshot.go
- docs/subcommands/Compute Engine/snapshot/create.md
- docs/subcommands/Compute Engine/snapshot/delete.md
- docs/subcommands/Compute Engine/snapshot/restore.md
- docs/subcommands/Compute Engine/snapshot/update.md
> fix #333: snapshot cols

- CHANGELOG.md
Updates changelog for v6.6.6 release
> doc: changelog v6.6.6

- .github/workflows/ci.yml
- .github/workflows/release.yml
> test: use IONOS_USERNAME and IONOS_PASSWORD secrets

- commands/cfg/cfg.go
- commands/cfg/location.go
- commands/root.go
- pkg/core/command_runner.go
(This is part of an effort to split #295 into multiple PRs)
Adds a `config location` command which prints the location of the config file
> feat: cfg location command

- commands/dataplatform/dataplatform_integration_test.go
If receiving a 403 Forbidden error, skip the test and print out more information about the datacenter, to help us and API team debug this issue.
> test: if 403 err for dataplatform, skip test and print datacenter information.

- pkg/jsontabwriter/jsontabwriter.go
Empty cols that were supposed to contain slices were not getting removed properly
> fix: empty slice cols now get properly removed

- commands/dns/zone/zone.go
Fix a missing Name column from DNS zones
> fix: missing name column for DNS zones

- CHANGELOG.md
- docs/subcommands/Compute Engine/config/location.md
- docs/subcommands/Compute Engine/config/login.md
- docs/subcommands/Compute Engine/config/logout.md
- docs/subcommands/Compute Engine/config/whoami.md
Update the changelog for the upcoming 6.7.0 release
> doc: changelog 6.7.0

- commands/token/token_integration_test.go
Token tests kept failing because creating and getting a token were not timed properly.
> fix: update token tests 

- CHANGELOG.md
- internal/printer/json2table/jsonpaths/cloudapi.go
Fix some issues with the printer paths
> fix: various printer fixes

- commands/dbaas/postgres/logs.go
- internal/printer/json2table/resource2table/dbaas.go
> Fix: postgres logs not printing

- CHANGELOG.md
Add missing changelog entries for release v6.7.3
> doc: changelog for release 6.7.3

- commands/cloudapi-v6/natgateway.go
> Fix: DatacenterId column for NatGW

- internal/printer/jsontabwriter/jsontabwriter.go
Use `reflect` functions when checking for slices.
> fix: slice check in printer pkg

- test/run.sh
Aggregate the non-zero exit codes of the BATS tests
> test: aggregate bats tests exit code

- commands/cloudapi-v6/image.go
- services/cloudapi-v6/resources/image.go
- test/bats/cloudapi/image.bats
Adds BATS E2E tests for Image Upload command
> test: image upload

- CHANGELOG.md
- commands/cloudapi-v6/k8s_nodepool_lan.go
> fix: k8s nodepool lans list error

- CHANGELOG.md
- README.md
> enhancement: remove basic auth deprecation notice from readme

- commands/cloudapi-v6/s3key.go
- commands/cloudapi-v6/user.go
- docs/subcommands/User-Management/create.md
- docs/subcommands/User-Management/delete.md
- docs/subcommands/User-Management/get.md
- docs/subcommands/User-Management/s3key/create.md
- docs/subcommands/User-Management/s3key/delete.md
- docs/subcommands/User-Management/s3key/get.md
- docs/subcommands/User-Management/s3key/list.md
- docs/subcommands/User-Management/s3key/update.md
- docs/subcommands/User-Management/update.md
- internal/printer/json2table/jsonpaths/cloudapi.go
- test/bats/cloudapi/image.bats
- test/bats/cloudapi/user.bats
Adds test for UM api (`user`, `group` commands), `token` commands, and `config` commands
> test: user, group, cfg, token commands

- .github/workflows/release.yml
- .goreleaser.yml
> feat: add snap release to goreleaser

- .goreleaser.yml
> fix: publish to candidate channel

- commands/dbaas/mongo/cluster/create.go
- test/bats/dbaas/mongodb.bats
> Fix: infer template from edition

- CHANGELOG.md
- commands/cfg/whoami.go
- internal/client/client.go
- test/bats/cloudapi/user.bats
Adresses https://github.com/ionos-cloud/ionosctl/issues/493
> enhancement: cfg file errors to output

- .github/workflows/issue-creation.yml
Fixes code scanning alert for the google chat issue notification workflow
> fix: code-scan issue title error 

- .github/workflows/issue-creation.yml
Turns the single quotes into double quotes and escapes existing double quotes
> fix: quotes google chat notification

- CHANGELOG.md
- commands/container-registry/registry/post.go
- commands/container-registry/registry/registries.go
- commands/container-registry/token/scopes/add.go
- commands/container-registry/token/scopes/delete.go
- commands/container-registry/token/scopes/list.go
- commands/container-registry/token/scopes/scopes.go
- docs/subcommands/Container-Registry/registry/create.md
- docs/subcommands/Container-Registry/registry/delete.md
- docs/subcommands/Container-Registry/registry/get.md
- docs/subcommands/Container-Registry/registry/list.md
- docs/subcommands/Container-Registry/registry/replace.md
- docs/subcommands/Container-Registry/registry/update.md
- docs/subcommands/Container-Registry/token/scope/add.md
- docs/subcommands/Container-Registry/token/scope/delete.md
- docs/subcommands/Container-Registry/token/scope/list.md
- internal/core/doc/flag.go
- internal/printer/json2table/jsonpaths/container-registry.go
- internal/printer/json2table/resource2table/container-registry.go
- Added missing container-registry columns
- The garbage collection days and time are now randomly generated to be a random working day during hours 10:00 - 16:00
- Fixed listing container-registry token scopes
- Fixed various panics related to nil ExpiryDate on container-registry tokens including #505
> fix: various container-registry fixes

- CHANGELOG.md
- test/bats/dbaas/mongodb.bats
> test: improve mongo bats tests, remove retry

- internal/core/doc/doc.go
Customizing `in-memory-db` doc generation would have required very messy and nested `if` statements on the already old and convoluted/unscale-able `determineSubdir` so it was time for a refactor.
Now you can easily define which command gets renamed to what, you can customize specific segments, append/prepend directories, etc
For example, if segments = `['my', 'little', 'pony']`, a rule of `{Prefix: []string{"my", "little", "pony"}, Template: "my/cute/{1+}"}`, would net a subdir structure of ✨ **my/cute/little/pony** ✨ !
NOTE: The documentation will still be generated the same. This is just to add better support for customizing the generated documentation directories.
> refactor: doc subdir generation. use templating

- CHANGELOG.md
adds changelog for upcoming 6.8.5 release
> doc: changelog 6.8.5

- CHANGELOG.md
Update changelog for 6.8.6 release
> doc: update changelog for v6.8.6

- commands/monitoring/pipeline/completer/completer.go
- commands/monitoring/pipeline/delete.go
- commands/monitoring/pipeline/pipeline.go
- docs/subcommands/Compute Engine/monitoring/pipeline/delete.md
- docs/summary.md
- internal/constants/constants.go
> feat: add Monitoring Pipeline Delete command 

- commands/monitoring/pipeline/completer/completer.go
- commands/monitoring/pipeline/get.go
- commands/monitoring/pipeline/pipeline.go
- docs/subcommands/Compute Engine/monitoring/pipeline/get.md
- docs/summary.md
- internal/constants/constants.go
> feat:add Monitoring Pipeline Get command

- docs/subcommands/Compute Engine/monitoring/pipeline/create.md
- docs/subcommands/Compute Engine/monitoring/pipeline/delete.md
- docs/subcommands/Compute Engine/monitoring/pipeline/get.md
- docs/subcommands/Compute Engine/monitoring/pipeline/list.md
- docs/subcommands/Compute Engine/monitoring/pipeline/update.md
- docs/summary.md
- test/bats/monitoring/monitoring.bats
> feat:/observability monitoring 2 tests

- CHANGELOG.md
- README.md
- docs/README.md
- docs/summary.md
> TWT-2397 Fix Broken Link

- .github/workflows/lint.yml
- .pre-commit-config.yaml
Adds golangci-lint workflow (lint.yml) and precommit-hook
> enhancement: add golangci-lint

- CHANGELOG.md
- commands/cloudapi-v6/completer/ids.go
Adds tab-completion information about templates
```
❯ i server create --type CUBE --template-id <TAB>                                                                                                                           
[7...af]  -- Basic Cube XS | 1 cores | 2 GB RAM | 60 GB | (Basic Templates)
...etc
```
> feat: --template-id tab-completion descriptions
